pub mod calculate_number_of_faction_cubes_in_space;
pub mod can_attack_remove_a_number_of_enemies_in_space;
pub mod does_space_have_support;
pub mod is_there_a_big_enough_concentration_of_coin_pieces_for_bombardment;
