use board::domain::city::City;
use board::domain::loc::LoC;
use board::domain::province::Province;
use board::domain::space::Spaces;
use board::domain::spaces_initialization::create_an_loc::create_an_loc;
use board::domain::spaces_initialization::create_hue::create_hue;
use board::domain::spaces_initialization::create_saigon::create_saigon;
use board::domain::spaces_initialization::create_the_fishhook::create_the_fishhook;
use game_definitions::geographic_areas::GeographicAreas;
use game_definitions::space_identifiers::SpaceIdentifiers;
use std::collections::HashMap;

pub fn initialize_hashmap_of_spaces() -> Result<HashMap<SpaceIdentifiers, Spaces>, String> {
    Ok([
        create_saigon(),
        create_hue(),
        create_an_loc(),
        (
            SpaceIdentifiers::KienGiangAnXuyen,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::Sihanoukville,
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::KienPhong,
                    SpaceIdentifiers::MekongNorth,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::BaXuyen,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::MekongSouth,
                    SpaceIdentifiers::KienHoaVinhBinh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangNam,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::DaNang,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::QuangTinQuangNgai,
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangTriThuaThien,
                    SpaceIdentifiers::SouthernLaos,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::BinhDinh,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::QuiNhon,
                    SpaceIdentifiers::Route1NorthEast,
                    SpaceIdentifiers::Route19,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::Kontum,
                    SpaceIdentifiers::Route14CentralNorth,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::QuangTinQuangNgai,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::CanTho,
            City::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::MekongSouth,
                    SpaceIdentifiers::KienHoaVinhBinh,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::KienPhong,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::KienPhong,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::KienHoaVinhBinh,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::KienGiangAnXuyen,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangTriThuaThien,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Hue,
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangNam,
                    SpaceIdentifiers::NorthVietnam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::NorthVietnam,
            Province::new(
                GeographicAreas::NorthVietnam,
                vec![
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangTriThuaThien,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::Sihanoukville,
            Province::new(
                GeographicAreas::Cambodia,
                vec![
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::KienGiangAnXuyen,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::TheParrotsBeak,
            Province::new(
                GeographicAreas::Cambodia,
                vec![
                    SpaceIdentifiers::Sihanoukville,
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::KienPhong,
                ],
            )
            .into(),
        ),
        create_the_fishhook(),
        (
            SpaceIdentifiers::QuangTinQuangNgai,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::DaNang,
                    SpaceIdentifiers::Route1NorthEast,
                    SpaceIdentifiers::BinhDinh,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::QuangNam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangDucLongKhanh,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route21,
                    SpaceIdentifiers::KhanhHoa,
                    SpaceIdentifiers::Route11,
                    SpaceIdentifiers::Route20,
                    SpaceIdentifiers::BinhTuyBinhThuan,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::Route14South,
                    SpaceIdentifiers::PhuocLong,
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::Route14Central,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::BinhTuyBinhThuan,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route20,
                    SpaceIdentifiers::Route21,
                    SpaceIdentifiers::Route11,
                    SpaceIdentifiers::Route1South,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::QuangDucLongKhanh,
                    SpaceIdentifiers::KhanhHoa,
                    SpaceIdentifiers::CamRanh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::PleikuDarlac,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route14South,
                    SpaceIdentifiers::Route21,
                    SpaceIdentifiers::Route14Central,
                    SpaceIdentifiers::Route14CentralNorth,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::QuangDucLongKhanh,
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::NortheastCambodia,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::Kontum,
                    SpaceIdentifiers::BinhDinh,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::KhanhHoa,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::CentralLaos,
            Province::new(
                GeographicAreas::Laos,
                vec![
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::QuangNam,
                    SpaceIdentifiers::QuangTriThuaThien,
                    SpaceIdentifiers::NorthVietnam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::SouthernLaos,
            Province::new(
                GeographicAreas::Laos,
                vec![
                    SpaceIdentifiers::Route14CentralNorth,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::NortheastCambodia,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::BinhDinh,
                    SpaceIdentifiers::QuangTinQuangNgai,
                    SpaceIdentifiers::QuangNam,
                    SpaceIdentifiers::CentralLaos,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuiNhon,
            City::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route19,
                    SpaceIdentifiers::Route1SouthEast,
                    SpaceIdentifiers::Route1East,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::BinhDinh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::KhanhHoa,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route1SouthEast,
                    SpaceIdentifiers::Route11,
                    SpaceIdentifiers::Route20,
                    SpaceIdentifiers::Route21,
                    SpaceIdentifiers::Route14South,
                    SpaceIdentifiers::Route14Central,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::CamRanh,
                    SpaceIdentifiers::BinhTuyBinhThuan,
                    SpaceIdentifiers::QuangDucLongKhanh,
                    SpaceIdentifiers::PleikuDarlac,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::KienHoaVinhBinh,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::MekongSouth,
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::KienPhong,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::PhuBonPhuYen,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route19,
                    SpaceIdentifiers::Route1SouthEast,
                    SpaceIdentifiers::Route14Central,
                    SpaceIdentifiers::KhanhHoa,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::Kontum,
                    SpaceIdentifiers::BinhDinh,
                    SpaceIdentifiers::QuiNhon,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::TayNinh,
            Province::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route13,
                    SpaceIdentifiers::Route14South,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::KienPhong,
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::AnLoc,
                    SpaceIdentifiers::PhuocLong,
                    SpaceIdentifiers::QuangDucLongKhanh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::Kontum,
            City::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route19,
                    SpaceIdentifiers::Route14Central,
                    SpaceIdentifiers::Route14CentralNorth,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::BinhDinh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::DaNang,
            City::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route1NorthEast,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::QuangTinQuangNgai,
                    SpaceIdentifiers::QuangNam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::CamRanh,
            City::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route1South,
                    SpaceIdentifiers::Route1SouthEast,
                    SpaceIdentifiers::Route11,
                    SpaceIdentifiers::BinhTuyBinhThuan,
                    SpaceIdentifiers::KhanhHoa,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::MekongNorth,
            LoC::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::KienPhong,
                    SpaceIdentifiers::TheParrotsBeak,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::Route4West,
            LoC::new(
                GeographicAreas::SouthVietnam,
                vec![
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::CanTho,
                ],
            )
            .into(),
        ),
    ]
    .iter()
    .cloned()
    .collect())
}
