#[derive(Hash, Debug, Clone, Copy, PartialEq)]
pub enum SpaceIdentifiers {
    Saigon,
    AnLoc,
    KienGiangAnXuyen,
    BaXuyen,
    QuangNam,
    BinhDinh,
    Route4,
    CanTho,
    Mekong,
    KienPhong,
    QuangTriThuaThien,
    NorthVietnam,
    TheParrotsBeak,
    QuangTinQuangNgai,
    QuangDucLongKhanh,
    BinhTuyBinhThuan,
    Hue,
    PleikuDarlac,
    CentralLaos,
    SouthernLaos,
    QuiNhon,
    KhanhHoa,
    KienHoaVinhBinh,
    PhuBonPhuYen,
    TayNinh,
    Kontum,
    DaNang,
    CamRanh,
}

impl Eq for SpaceIdentifiers {}
