pub const NVA_RESOURCES_AT_WHICH_NVA_WILL_PASS: u8 = 0;
pub const MAXIMUM_TRAIL_NUMBER_UNDER_WHICH_NVA_WILL_ATTEMPT_TO_RALLY: u8 = 2;
pub const MAXIMUM_NUMBER_OF_NVA_UNITS_ANY_BASE_MUST_BE_PROTECTED_BY_UNDER_WHICH_NVA_WILL_ATTEMPT_TO_RALLY: u8 = 2;
pub const MINIMUM_NUMBER_OF_NVA_TROOPS_THAT_SHOULD_BE_PLACED_THROUGH_INFILTRATE_TO_GO_AHEAD_WITH_IT: u8 =  4;
