pub const NVA_RESOURCES_AT_WHICH_NVA_WILL_PASS: u8 = 0;
pub const MAXIMUM_TRAIL_NUMBER_UNDER_WHICH_NVA_WILL_ATTEMPT_TO_RALLY: u8 = 2;
pub const MAXIMUM_NUMBER_OF_NVA_UNITS_ANY_BASE_MUST_BE_PROTECTED_BY_UNDER_WHICH_NVA_WILL_ATTEMPT_TO_RALLY: u8 = 2;
