use board::domain::city::City;
use board::domain::loc::LoC;
use board::domain::province::Province;
use board::domain::space::Spaces;
use game_definitions::geographic_area::GeographicArea;
use game_definitions::space_identifiers::SpaceIdentifiers;
use std::collections::HashMap;

pub fn initialize_hashmap_of_spaces() -> Result<HashMap<SpaceIdentifiers, Spaces>, String> {
    Ok([
        (
            SpaceIdentifiers::Saigon,
            City::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::KienHoaVinhBinh,
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::KienPhong,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::Route13,
                    SpaceIdentifiers::Route14South,
                    SpaceIdentifiers::QuangDucLongKhanh,
                    SpaceIdentifiers::BinhTuyBinhThuan,
                    SpaceIdentifiers::Route20,
                    SpaceIdentifiers::Route1South,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::Hue,
            City::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::QuangTriThuaThien,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::AnLoc,
            City::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::PhuocLong,
                    SpaceIdentifiers::Route13,
                    SpaceIdentifiers::TayNinh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::KienGiangAnXuyen,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::Sihanoukville,
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::KienPhong,
                    SpaceIdentifiers::MekongNorth,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::BaXuyen,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::MekongSouth,
                    SpaceIdentifiers::KienHoaVinhBinh,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangNam,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::DaNang,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::QuangTinQuangNgai,
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangTriThuaThien,
                    SpaceIdentifiers::SouthernLaos,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::BinhDinh,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::QuiNhon,
                    SpaceIdentifiers::Route1NorthEast,
                    SpaceIdentifiers::Route19,
                    SpaceIdentifiers::PhuBonPhuYen,
                    SpaceIdentifiers::Kontum,
                    SpaceIdentifiers::Route14CentralNorth,
                    SpaceIdentifiers::PleikuDarlac,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::QuangTinQuangNgai,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::CanTho,
            City::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::MekongSouth,
                    SpaceIdentifiers::KienHoaVinhBinh,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::Route4West,
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::KienPhong,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::KienPhong,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::Route4MekongEast,
                    SpaceIdentifiers::Saigon,
                    SpaceIdentifiers::KienHoaVinhBinh,
                    SpaceIdentifiers::CanTho,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::KienGiangAnXuyen,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangTriThuaThien,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::Hue,
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangNam,
                    SpaceIdentifiers::NorthVietnam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::NorthVietnam,
            Province::new(
                GeographicArea::NorthVietnam,
                vec![
                    SpaceIdentifiers::Route1North,
                    SpaceIdentifiers::CentralLaos,
                    SpaceIdentifiers::QuangTriThuaThien,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::Sihanoukville,
            Province::new(
                GeographicArea::Cambodia,
                vec![
                    SpaceIdentifiers::TheParrotsBeak,
                    SpaceIdentifiers::KienGiangAnXuyen,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::TheParrotsBeak,
            Province::new(
                GeographicArea::Cambodia,
                vec![
                    SpaceIdentifiers::Sihanoukville,
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::MekongNorth,
                    SpaceIdentifiers::TheFishhook,
                    SpaceIdentifiers::TayNinh,
                    SpaceIdentifiers::KienPhong,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangTinQuangNgai,
            Province::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::DaNang,
                    SpaceIdentifiers::Route1NorthEast,
                    SpaceIdentifiers::BinhDinh,
                    SpaceIdentifiers::Route14North,
                    SpaceIdentifiers::SouthernLaos,
                    SpaceIdentifiers::QuangNam,
                ],
            )
            .into(),
        ),
        (
            SpaceIdentifiers::QuangDucLongKhanh,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::BinhTuyBinhThuan,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::PleikuDarlac,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::CentralLaos,
            Province::new(GeographicArea::Laos, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::SouthernLaos,
            Province::new(GeographicArea::Laos, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::QuiNhon,
            City::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::KhanhHoa,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::KienHoaVinhBinh,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::PhuBonPhuYen,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::TayNinh,
            Province::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::Kontum,
            City::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::DaNang,
            City::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::CamRanh,
            City::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::MekongNorth,
            LoC::new(GeographicArea::SouthVietnam, Vec::new()).into(),
        ),
        (
            SpaceIdentifiers::Route4West,
            LoC::new(
                GeographicArea::SouthVietnam,
                vec![
                    SpaceIdentifiers::KienGiangAnXuyen,
                    SpaceIdentifiers::BaXuyen,
                    SpaceIdentifiers::CanTho,
                ],
            )
            .into(),
        ),
    ]
    .iter()
    .cloned()
    .collect())
}
