pub fn does_typed_command_refer_to_space(typed_input_command: &str) -> bool {
    typed_input_command == "north vietnam"
        || typed_input_command == "saigon"
        || typed_input_command == "an loc"
        || typed_input_command == "can tho"
        || typed_input_command == "the parrot's beak"
        || typed_input_command == "kien phong"
        || typed_input_command == "kien giang"
        || typed_input_command == "quang tri"
        || typed_input_command == "binh dinh"
        || typed_input_command == "pleiku"
        || typed_input_command == "hue"
        || typed_input_command == "quang tin"
        || typed_input_command == "quang duc"
        || typed_input_command == "binh tuy"
}
